### PR TITLE
a simple css-grid implementation

### PR DESCRIPTION
**Pull request by Player256**

### CODE REVIEW

**Review by IshitaSatpathy — CHANGES_REQUESTED** [review]
serves none of the issues ... pls adhere and submit a pr

**Comment by Player256** [comment]
You can create an issue naming css-grid implementation if thats the case.

**Comment by IshitaSatpathy** [comment]
We have a defined set of issues.... if u can solve any amongst them it would be great. Make sure to mention the issue you are trying to resolve when u submit a PR.

**Comment by Player256** [comment]
Hey, can you create an issue for something like auth implementation. I have an implementation using ts. It would be great for rasing multiple issues around that one project

**Pull request closed without merging**
